### PR TITLE
Adding Portuguese baseline and Portuguese (Portugal)

### PR DESCRIPTION
**Pull request by ner00**
The baseline is added to serve other Portuguese-speaking users not immediately covered by the Brazilian or European variants, like Angola or Mozambique.

I just now noticed the Transifex project, do you want me to cancel this PR and go through Transifex? I'm fairly familiar with its, but since this seems to be the first implementation of this particular language maybe you can pull directly?

Thanks for the awesome work!

### CODE REVIEW

**Comment by prsnbrg** [comment]
Hi!
Please add the translations in values-* via [Transifex](https://www.transifex.com/a-302/qr-barcode-scanner/).

Everything else looks good to me.

**Comment by ner00** [comment]
I have requested but haven't been accepted to the translation team so far.

Since the language/s is in a blank state the project manager over at Transifex could as well just import the files, but if not I'll gladly go over the painstaking task of adding them manually, all I really need it to have translation access to the languages involved.

**Comment by prsnbrg** [comment]
You can add the changes and additions in /fastlane/metadata/android/ to the repo via a pull request.

**Comment by ner00** [comment]
> Hi! Please add the translations in values-* via [Transifex](https://www.transifex.com/a-302/qr-barcode-scanner/).

This turned out to be terrible advice, given that the translation work from Transifex was completely ignored, and in fact, only those pushed through here were actually ever pulled and merged into the actual release.

I've pushed https://github.com/wewewe718/QrAndBarcodeScanner/pull/128/files to reflect this inconsistency in the README since it is also inaccurate as to the mechanics of merging new translations, or updates to existing ones for that matter.

**Pull request closed without merging**
